apiVersion: apps/v1
kind: Deployment
metadata:
  name: spots-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: spots
  template:
    metadata:
      labels:
        name: spots
    spec:
      containers:
        - name: spots
          image: coffee51/spots
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-service:4222'
            - name: NATS_CLUSTER_ID
              value: spotty
            - name: MONGO_URL
              value: 'mongodb://spots-mongo-service:27017/spots'
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET