apiVersion: apps/v1
kind: Deployment
metadata:
    name: client-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            name: client
    template:
        metadata:
            labels:
                name: client
        spec:
            containers:
                - name: client
                  image: coffee51/client