apiVersion: skaffold/v2alpha3
kind: Config
deploy:
    kubectl:
        manifests:
            - ./kubernetes/*
build:
    local:
        push: false
    artifacts:
        - image: coffee51/authentication
          context: authentication
          docker:
              dockerfile: Dockerfile
          sync: 
            manual:
              - src: "src/**/*.ts"
                dest: .
        - image: coffee51/spots
          context: spots
          docker:
              dockerfile: Dockerfile
          sync: 
            manual:
              - src: "src/**/*.ts"
                dest: .
        - image: coffee51/comments
          context: comments
          docker:
              dockerfile: Dockerfile
          sync: 
            manual:
              - src: "src/**/*.ts"
                dest: .
        - image: coffee51/query
          context: query
          docker:
              dockerfile: Dockerfile
          sync: 
            manual:
              - src: "src/**/*.ts"
                dest: .