name: tests-auth-longpolling

on:
  pull_request:
    paths: 
      - "longPolling/authentication/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd longPolling/authentication && npm install && npm run test:remote
