name: tests-query-longpolling

on:
  pull_request:
    paths: 
      - "longPolling/query/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd longPolling/query && npm install && npm run test:remote
