name: tests-spots-longpolling

on:
  pull_request:
    paths: 
      - "longPolling/spots/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd longPolling/spots && npm install && npm run test:remote
