name: tests-comments-longpolling

on:
  pull_request:
    paths: 
      - "longPolling/comments/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd longPolling/comments && npm install && npm run test:remote
