name: tests-auth-polling

on:
  pull_request:
    paths: 
      - "polling/authentication/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd polling/authentication && npm install && npm run test:remote
