name: tests-query-polling

on:
  pull_request:
    paths: 
      - "polling/query/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd polling/query && npm install && npm run test:remote
