name: tests-comments

on:
  pull_request:
    paths: 
      - "polling/comments/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd polling/comments && npm install && npm run test:remote
