name: tests-auth

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd polling/authentication && npm install && npm run test:remote
