name: tests-spots

on:
  pull_request:
    paths: 
      - "websockets/spots/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd websockets/spots && npm install && npm run test:remote
