name: tests-query

on:
  pull_request:
    paths: 
      - "websockets/query/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd websockets/query && npm install && npm run test:remote
