name: tests-comments-websockets

on:
  pull_request:
    paths: 
      - "websockets/comments/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd websockets/comments && npm install && npm run test:remote
