apiVersion: v1
kind: Service
metadata:
    name: authentication-service
spec:
    selector:
        name: authentication
    ports:
        - name: authentication
          protocol: TCP
          port: 4000
          targetPort: 4000